version: '3'
services:
  redis:
    image: "redis:3.2-alpine"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:9.6.6-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cajitos
  rabbit:
    image: "rabbitmq:3-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.8.3"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
