version: '1'
services:
  redis:
    image: "redis:3.2-alpine"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:9.6.6-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cajitos
